
@SoporteLab_Api = http://localhost:5072
@SoporteLab_Web = http://localhost:5031



### 1. Listar todos los tickets en formato JSON
GET {{SoporteLab_Api}}/api/tickets
Accept: application/json

###

### 2. Crear un nuevo ticket de prueba
POST {{SoporteLab_Api}}/api/tickets
Content-Type: application/json

{
  "titulo": "Fallo en conexión WiFi",
  "descripcion": "No hay acceso a internet en el laboratorio de redes desde las 8:00 AM.",
  "categoria": "Redes",
  "prioridad": "Alta",
  "estado": "Nuevo",
  "solicitante": "Isaac Vega"
}

###

### 3. Consultar un ticket específico por su ID
GET {{SoporteLab_Api}}/api/tickets/1
Accept: application/json

###

### 4. Actualizar el estado o prioridad de un ticket existente
PUT {{SoporteLab_Api}}/api/tickets/1
Content-Type: application/json

{
  "id": 1,
  "titulo": "Fallo en conexión WiFi - EN PROCESO",
  "descripcion": "El router principal fue revisiciado y se está validando la estabilidad.",
  "categoria": "Redes",
  "prioridad": "Alta",
  "estado": "En proceso",
  "solicitante": "Isaac Vega"
}

###

### 5. Eliminar un ticket de la base de datos SQLite
DELETE {{SoporteLab_Api}}/api/tickets/1
Accept: application/json


### 6. Verificar conectividad con la interfaz de usuario Blazor
GET {{SoporteLab_Web}}/